With cte as
(
SELECT  
STARTED_AT,
TO_TIMESTAMP(REPLACE(STARTED_AT, '"', '')) AS STARTED_AT_TRANSFORMED,
DATE(TO_TIMESTAMP(REPLACE(STARTED_AT, '"', ''))) AS DATE_VALUE,
MONTH(TO_TIMESTAMP(REPLACE(STARTED_AT, '"', ''))) AS MONTH_VALUE,
HOUR(TO_TIMESTAMP(REPLACE(STARTED_AT, '"', ''))) AS HOUR_VALUE,
DAYNAME(TO_TIMESTAMP(REPLACE(STARTED_AT, '"', ''))) AS DAYNAME,
CASE WHEN DAYNAME IN ('Sat','Sun') then 'Weekend'
ELSE 'BUSINESSDAY' END AS DAY_TYPE
FROM {{ source('DEMO', 'BIKE') }}    
)
SELECT *
FROM CTE